#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx

if ! pgrep nginx &> /dev/null; then
    sudo service nginx start
fi

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
